#!/usr/bin/env bash
# A Bash scrit to archive all MySQL DATABASE with the help of mysqldump and tar.
password="$1"
backup_filename="$(date +%d-%m-%Y).tar.gz"

# Perform the MySQL dump and save it to a file
mysqldump -uroot -p"$password" --all-databases > backup.sql

# Create a tar-gzipped archive of the backup file
tar -cvzf "$backup_filename" backup.sql
