#!/usr/bin/env bash
# This script loops from 1 t 10
# Displays "bad luck" for the 4th loop iteration
# Displays "good luck" for the 8th loop iteration
# Displays "Best School" for the other iterations
# Must use while loop, if, elif and else statements
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
	echo "bad luck"
	elif [ $i -eq 8 ]
	then
	echo "good luck"
	else
	echo "Best School"
	fi
	((i++))
done
