#!/usr/bin/env bash

# Initialize the variable i to 1
i=1

# Using a while loop to display numbers from 1 to 20
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "4 and then bad luck from China"
			;;
    		9)
      			echo "9 and then bad luck from Japan"
      			;;
    		17)
      			echo "17 and then bad luck from Italy"
      			;;
    		*)
      			echo $i
      			;;
  	esac

  	((i++))
done

