#!/usr/bin/env bash
# Run Nginx as Nginx
#nginx must be listening on all active IPs on port 8080

chmod 644 /etc/nginx/nginx.conf
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
